spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/FirstProject?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 12341234

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql : true
    properties :
      hibernate :
        format_sql : true

  jwt:
    secret-key-source: ${JWT_SECRET_KEY}

