spring:
  datasource:
    url: jdbc:mysql://localhost:3306/FirstProject?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: k2winner*
    driver-class-name:

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql : true
    properties :
      hibernate :
        format_sql : true
        show_sql : true